//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("lefthook.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("line.jpg")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("pyramid.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("righthook.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("sides.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("square.jpg")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("ups.png")]


